#!/usr/bin/env python3
"""Generate and validate the deterministic M09 command and permission inventories."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[2]
COMMAND_JSON = ROOT / "build" / "m09-command-inventory.json"
PERMISSION_JSON = ROOT / "build" / "m09-permission-inventory.json"
COMMAND_DOC = ROOT / "docs" / "COMMANDS.md"
PERMISSION_DOC = ROOT / "docs" / "PERMISSIONS.md"

FAMILIES = (
    ("arena", ("list", "status", "health", "create", "rename", "enable", "disable",
     "delete", "duplicate", "import", "export", "backup", "restore", "validate",
     "diagnostics"), "arena", ("ZBW-ARENA-001", "ZBW-ARENA-003", "ZBW-ARENA-004",
     "ZBW-ARENA-006", "ZBW-ARENA-007", "ZBW-ARENA-009", "ZBW-UX-001", "ZBW-UX-006")),
    ("setup", ("start", "progress", "edit", "team", "spawn", "bed", "generator",
     "shop-location", "upgrade-location", "region", "property", "markers", "preview",
     "apply", "undo", "redo", "save", "rollback", "status", "exit"), "setup",
     tuple(f"ZBW-ADDON-{value:03d}" for value in range(408, 424))
     + ("ZBW-ARENA-002", "ZBW-ARENA-005", "ZBW-ARENA-008", "ZBW-ARENA-009",
        "ZBW-UX-001", "ZBW-UX-002", "ZBW-UX-003", "ZBW-UX-006")),
    ("game", ("join", "leave", "lobby-status", "match-status", "start", "force-start",
     "stop", "recover", "reconnect-diagnostics", "restoration-diagnostics", "health",
     "diagnostics"), "game", ("ZBW-GAME-001", "ZBW-GAME-002", "ZBW-GAME-003",
     "ZBW-GAME-006", "ZBW-GAME-008", "ZBW-GAME-010", "ZBW-UX-001", "ZBW-UX-006")),
    ("hotbar-manager", ("edit", "preview", "reload", "validate", "inspect"),
     "hotbar.manager", tuple(f"ZBW-ADDON-{value:03d}" for value in range(1, 10))),
    ("deposit", ("hand", "resources", "all", "reload", "inspect"), "deposit",
     tuple(f"ZBW-ADDON-{value:03d}" for value in range(108, 115))),
    ("arena-start-message", ("edit", "preview", "reload", "validate", "inspect"),
     "arena.start.message", tuple(f"ZBW-ADDON-{value:03d}" for value in range(124, 131))),
    ("anti-drop", ("edit", "preview", "reload", "validate", "inspect"), "anti.drop",
     tuple(f"ZBW-ADDON-{value:03d}" for value in range(148, 155))),
    ("leave-delay", ("edit", "preview", "reload", "validate", "inspect"), "leave.delay",
     tuple(f"ZBW-ADDON-{value:03d}" for value in range(334, 341))),
    ("tab-sorter", ("edit", "preview", "reload", "validate", "inspect"), "tab.sorter",
     tuple(f"ZBW-ADDON-{value:03d}" for value in range(398, 408))),
    ("bossbar", ("edit", "preview", "reload", "validate", "inspect"), "bossbar",
     tuple(f"ZBW-ADDON-{value:03d}" for value in range(424, 432))),
    ("adventure-mode", ("edit", "preview", "reload", "validate", "inspect"),
     "adventure.mode", tuple(f"ZBW-ADDON-{value:03d}" for value in range(432, 438))),
)


def inventory() -> list[dict[str, object]]:
    """Return the same append-only action inventory represented by PresentationActions.Catalog."""
    rows: list[dict[str, object]] = []
    for family, operations, permission_family, requirements in FAMILIES:
        for operation in operations:
            direct_deposit = family == "deposit" and operation in {"hand", "resources", "all"}
            command = f"/deposit {operation}" if direct_deposit else f"/zbw {family} {operation}"
            rows.append({
                "action_id": f"zartra:action/{family}/{operation}",
                "command": command,
                "gui_page": f"zartra:m09/{family}/{operation}",
                "permission": "zartrabedwars." + permission_family + "." + operation.replace("-", "."),
                "destructive": operation in {"delete", "restore", "rollback", "stop", "reset", "apply"},
                "requirement_ids": list(requirements),
            })
    if len(rows) != 87 or len({row["action_id"] for row in rows}) != 87:
        raise ValueError("the M09 action inventory must contain exactly 87 unique actions")
    return rows


def render() -> dict[Path, str]:
    rows = inventory()
    command_payload = {"schema_version": 1, "milestone": "M09", "count": len(rows), "commands": rows}
    permissions = sorted({str(row["permission"]) for row in rows})
    permission_payload = {
        "schema_version": 1,
        "milestone": "M09",
        "count": len(permissions),
        "authorization_source": "M03 AuthorizationService",
        "permissions": permissions,
    }
    command_lines = [
        "# Command inventory",
        "",
        "Generated by `tools/validation/m09_inventories.py`; manual edits are rejected.",
        "All labels dispatch through the neutral command tree and M03 authorization service.",
        "",
        "| Command | Action | GUI parity page | Permission | Confirmation |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        command_lines.append(
            f"| `{row['command']}` | `{row['action_id']}` | `{row['gui_page']}` | "
            f"`{row['permission']}` | {'required' if row['destructive'] else 'not required'} |"
        )
    permission_lines = [
        "# Permission inventory",
        "",
        "Generated by `tools/validation/m09_inventories.py`; manual edits are rejected.",
        "Nodes are additive and granular. Console/player identity, role grants and revocation are",
        "resolved centrally; operator status is not an authorization policy.",
        "",
        "| Permission | Surface | Enforcement |",
        "|---|---|---|",
    ]
    for permission in permissions:
        permission_lines.append(
            f"| `{permission}` | command and GUI | execution-time M03 authorization revalidation |"
        )
    return {
        COMMAND_JSON: json.dumps(command_payload, indent=2, sort_keys=True) + "\n",
        PERMISSION_JSON: json.dumps(permission_payload, indent=2, sort_keys=True) + "\n",
        COMMAND_DOC: "\n".join(command_lines) + "\n",
        PERMISSION_DOC: "\n".join(permission_lines) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    arguments = parser.parse_args()
    failures: list[str] = []
    for path, expected in render().items():
        if arguments.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
        elif not path.is_file() or path.read_text(encoding="utf-8") != expected:
            failures.append(str(path.relative_to(ROOT)))
    source = (ROOT / "command/zbw-command-api/src/main/java/io/zartra/bedwars/command/api/PresentationActions.java").read_text(encoding="utf-8")
    for family, operations, _, _ in FAMILIES:
        if f'"{family}"' not in source or any(f'"{operation}"' not in source for operation in operations):
            failures.append(f"PresentationActions.Catalog:{family}")
    if failures:
        print("ERROR: stale or incomplete M09 inventory: " + ", ".join(failures), file=sys.stderr)
        return 1
    print("M09 inventories PASS: 87 actions, 87 granular permissions, deterministic docs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
