#!/usr/bin/env python3
"""Generate deterministic through-M10 command and permission inventories."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import m09_inventories


ROOT = Path(__file__).resolve().parents[2]
COMMAND_JSON = ROOT / "build/m10-command-inventory.json"
PERMISSION_JSON = ROOT / "build/m10-permission-inventory.json"
COMMAND_DOC = ROOT / "docs/COMMANDS.md"
PERMISSION_DOC = ROOT / "docs/PERMISSIONS.md"

FAMILIES = (
    ("selector", ("quick-join", "arena", "mode", "map", "layout", "team-size"), "selector", False),
    ("queue", ("join", "leave", "status"), "matchmaking.queue", False),
    ("spectator", ("enter", "leave", "target", "next", "previous", "status", "options"), "spectator", False),
    ("compass", ("track", "communications"), "compass", False),
    ("team-selector", ("open", "select", "clear", "status"), "team.selector", False),
    ("admin-matchmaking", ("diagnostics", "reservations"), "admin.matchmaking", False),
    ("admin-mode", ("list", "validate", "enable", "disable"), "admin.mode", True),
)


def inventory() -> list[dict[str, object]]:
    """Return the append-only M09 baseline and M10 actions."""
    rows = list(m09_inventories.inventory())
    for family, operations, permission_family, administrative in FAMILIES:
        for operation in operations:
            requirements = ["ZBW-GAME-007"]
            if family == "selector":
                requirements = ["ZBW-GAME-007", "ZBW-CONTENT-003"]
            elif family == "spectator":
                requirements = ["ZBW-GAME-009"] + [f"ZBW-ADDON-{value:03d}" for value in range(92, 102)] + [f"ZBW-ADDON-{value:03d}" for value in range(115, 124)]
            elif family == "compass":
                requirements = [f"ZBW-ADDON-{value:03d}" for value in range(131, 141)]
            elif family == "team-selector":
                requirements = [f"ZBW-ADDON-{value:03d}" for value in range(155, 164)]
            elif family == "admin-mode":
                requirements = ["ZBW-GAME-004", "ZBW-GAME-005", "ZBW-CONTENT-003"] + [f"ZBW-ADDON-{value:03d}" for value in range(236, 245)]
            rows.append({
                "action_id": f"zartra:action/{family}/{operation}",
                "command": f"/zbw {family.replace('admin-', 'admin ')} {operation}",
                "gui_page": f"zartra:m10/{family}/{operation}",
                "permission": "zartrabedwars." + permission_family + "." + operation.replace("-", "."),
                "destructive": administrative and operation in {"enable", "disable"},
                "requirement_ids": requirements,
            })
    if len(rows) != 115 or len({row["action_id"] for row in rows}) != 115:
        raise ValueError("through-M10 inventory must contain 115 unique actions")
    return rows


def render() -> dict[Path, str]:
    rows = inventory()
    permissions = sorted({str(row["permission"]) for row in rows})
    command_payload = {"schema_version": 1, "milestone": "M10", "baseline": 87,
                       "additive": 28, "count": 115, "commands": rows}
    permission_payload = {"schema_version": 1, "milestone": "M10", "baseline": 87,
                          "additive": 28, "count": 115,
                          "authorization_source": "M03 AuthorizationService",
                          "permissions": permissions}
    command_lines = ["# Command inventory", "", "Generated by `tools/validation/m10_inventories.py`; manual edits are rejected.",
                     "All 115 labels dispatch through the neutral M09 command tree and M03 authorization.", "",
                     "| Command | Action | GUI parity page | Permission | Confirmation |", "|---|---|---|---|---|"]
    for row in rows:
        command_lines.append(f"| `{row['command']}` | `{row['action_id']}` | `{row['gui_page']}` | `{row['permission']}` | {'required' if row['destructive'] else 'not required'} |")
    permission_lines = ["# Permission inventory", "", "Generated by `tools/validation/m10_inventories.py`; manual edits are rejected.",
                        "All nodes are additive, granular and revalidated at execution time; operator status is not policy.", "",
                        "| Permission | Surface | Enforcement |", "|---|---|---|"]
    permission_lines.extend(f"| `{permission}` | command and GUI | execution-time M03 authorization revalidation |" for permission in permissions)
    return {COMMAND_JSON: json.dumps(command_payload, indent=2, sort_keys=True) + "\n",
            PERMISSION_JSON: json.dumps(permission_payload, indent=2, sort_keys=True) + "\n",
            COMMAND_DOC: "\n".join(command_lines) + "\n",
            PERMISSION_DOC: "\n".join(permission_lines) + "\n"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in render().items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")
        elif not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        print("ERROR: stale M10 inventories: " + ", ".join(stale), file=sys.stderr)
        return 1
    print("M10 inventories PASS: 115 actions, 115 permissions, 116 dashboard-inclusive GUI pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
