#!/usr/bin/env python3
"""Generate deterministic through-M11 command and permission inventories."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import m10_inventories

ROOT = Path(__file__).resolve().parents[2]
COMMAND_JSON = ROOT / "build/m11-command-inventory.json"
PERMISSION_JSON = ROOT / "build/m11-permission-inventory.json"
COMMAND_DOC = ROOT / "docs/COMMANDS.md"
PERMISSION_DOC = ROOT / "docs/PERMISSIONS.md"

FAMILIES = (
    ("shop", ("open", "quick-buy", "favourites", "history", "rotation", "inspect"), "shop", ("ZBW-SHOP-001", "ZBW-SHOP-002", "ZBW-SHOP-003", "ZBW-SHOP-004")),
    ("upgrade", ("open", "purchase", "status", "inspect"), "upgrade", ("ZBW-SHOP-005",)),
    ("generator", ("status", "validate", "inspect"), "generator", ("ZBW-SHOP-006",)),
    ("utility", ("use", "status", "inspect"), "item", ("ZBW-SHOP-007",)),
    ("popup-towers", ("preview", "validate", "inspect"), "popup.towers", tuple(f"ZBW-ADDON-{value:03d}" for value in range(184, 194))),
    ("sponge-effects", ("preview", "validate", "inspect"), "sponge.effects", tuple(f"ZBW-ADDON-{value:03d}" for value in range(141, 148))),
    ("item-rotation", ("status", "validate", "inspect"), "item.rotation", tuple(f"ZBW-ADDON-{value:03d}" for value in range(379, 389))),
)

def inventory() -> list[dict[str, object]]:
    rows = list(m10_inventories.inventory())
    for family, operations, permission_family, requirements in FAMILIES:
        for operation in operations:
            rows.append({"action_id": f"m11/{family}/{operation}",
                         "command": f"/zbw {family} {operation}",
                         "gui_page": f"zartra:m11/{family}/{operation}",
                         "permission": f"zartrabedwars.{permission_family}.{operation.replace('-', '.')}",
                         "destructive": False, "requirement_ids": list(requirements)})
    if len(rows) != 140 or len({row["action_id"] for row in rows}) != 140:
        raise ValueError("through-M11 inventory must contain 140 unique actions")
    return rows

def render() -> dict[Path, str]:
    rows = inventory()
    permissions = sorted({str(row["permission"]) for row in rows})
    commands = {"schema_version": 1, "milestone": "M11", "baseline": 115,
                "additive": 25, "count": 140, "commands": rows}
    permission_payload = {"schema_version": 1, "milestone": "M11", "baseline": 115,
                          "additive": 25, "count": len(permissions),
                          "authorization_source": "M03 AuthorizationService",
                          "permissions": permissions}
    command_lines = ["# Command inventory", "", "Generated by `tools/validation/m11_inventories.py`; manual edits are rejected.",
                     "All 140 labels dispatch through the M09 framework and central M03 authorization.", "",
                     "| Command | Action | GUI parity page | Permission | Confirmation |", "|---|---|---|---|---|"]
    for row in rows:
        command_lines.append(f"| `{row['command']}` | `{row['action_id']}` | `{row['gui_page']}` | `{row['permission']}` | {'required' if row['destructive'] else 'not required'} |")
    permission_lines = ["# Permission inventory", "", "Generated by `tools/validation/m11_inventories.py`; manual edits are rejected.",
                        "All nodes are granular and revalidated by central authorization.", "",
                        "| Permission | Surface | Enforcement |", "|---|---|---|"]
    permission_lines.extend(f"| `{permission}` | command and GUI | execution-time M03 authorization |" for permission in permissions)
    return {COMMAND_JSON: json.dumps(commands, indent=2, sort_keys=True) + "\n",
            PERMISSION_JSON: json.dumps(permission_payload, indent=2, sort_keys=True) + "\n",
            COMMAND_DOC: "\n".join(command_lines) + "\n",
            PERMISSION_DOC: "\n".join(permission_lines) + "\n"}

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in render().items():
        if args.write:
            path.write_text(expected, encoding="utf-8", newline="\n")
        elif not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        print("ERROR: stale M11 inventories: " + ", ".join(stale), file=sys.stderr)
        return 1
    print(f"M11 inventories PASS: {len(inventory())} actions and GUI pages")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
