#!/usr/bin/env python3
"""Generate deterministic through-M12 command and permission inventories."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import m11_inventories

ROOT = Path(__file__).resolve().parents[2]
COMMAND_JSON = ROOT / "build/m12-command-inventory.json"
PERMISSION_JSON = ROOT / "build/m12-permission-inventory.json"
COMMAND_DOC = ROOT / "docs/COMMANDS.md"
PERMISSION_DOC = ROOT / "docs/PERMISSIONS.md"

FAMILIES = (
    ("progression", ("view", "level", "xp", "prestige"), "progression", False,
     ("ZBW-PROG-001", "ZBW-PROG-002", "ZBW-PROG-003", "ZBW-PROG-004")),
    ("currency", ("balances",), "currency", False, ("ZBW-PROG-005",)),
    ("reward", ("list", "claim", "unlocks"), "reward", False,
     ("ZBW-PROG-005", "ZBW-PROG-011")),
    ("admin-progression", ("inspect", "grant-xp", "adjust", "recalculate"),
     "progression", True,
     ("ZBW-PROG-001", "ZBW-PROG-002", "ZBW-PROG-003", "ZBW-PROG-004")),
    ("admin-reward", ("inspect", "grant", "failures"), "reward", True,
     ("ZBW-PROG-005", "ZBW-PROG-011")),
    ("admin-currency", ("inspect", "ledger"), "currency", True, ("ZBW-PROG-005",)),
)

MUTATIONS = {"claim", "grant", "grant-xp", "adjust", "recalculate"}


def inventory() -> list[dict[str, object]]:
    rows = list(m11_inventories.inventory())
    for family, operations, permission_family, administrative, requirements in FAMILIES:
        for operation in operations:
            command_family = f"admin {family[6:]}" if family.startswith("admin-") else family
            admin_segment = "admin." if administrative else ""
            rows.append({"action_id": f"m12/{family}/{operation}",
                         "command": f"/zbw {command_family} {operation}",
                         "gui_page": f"zartra:m12/{family}/{operation}",
                         "permission": (f"zartrabedwars.{permission_family}.{admin_segment}"
                                        f"{operation.replace('-', '.') }"),
                         "destructive": operation in MUTATIONS,
                         "requirement_ids": list(requirements)})
    if len(rows) != 157 or len({row["action_id"] for row in rows}) != 157:
        raise ValueError("through-M12 inventory must contain 157 unique actions")
    return rows


def render() -> dict[Path, str]:
    rows = inventory()
    permissions = sorted({str(row["permission"]) for row in rows})
    commands = {"schema_version": 1, "milestone": "M12", "baseline": 140,
                "additive": 17, "count": 157, "commands": rows}
    permission_payload = {"schema_version": 1, "milestone": "M12", "baseline": 140,
                          "additive": 17, "count": len(permissions),
                          "authorization_source": "M03 AuthorizationService",
                          "permissions": permissions}
    command_lines = ["# Command inventory", "",
                     "Generated by `tools/validation/m12_inventories.py`; manual edits are rejected.",
                     "All 157 labels dispatch through M09 and central M03 authorization.", "",
                     "| Command | Action | GUI parity page | Permission | Confirmation |",
                     "|---|---|---|---|---|"]
    for row in rows:
        confirmation = "required" if row["destructive"] else "not required"
        command_lines.append(f"| `{row['command']}` | `{row['action_id']}` | "
                             f"`{row['gui_page']}` | `{row['permission']}` | {confirmation} |")
    permission_lines = ["# Permission inventory", "",
                        "Generated by `tools/validation/m12_inventories.py`; manual edits are rejected.",
                        "All nodes are granular and revalidated by central authorization.", "",
                        "| Permission | Surface | Enforcement |", "|---|---|---|"]
    permission_lines.extend(f"| `{permission}` | command and GUI | execution-time M03 authorization |"
                            for permission in permissions)
    return {COMMAND_JSON: json.dumps(commands, indent=2, sort_keys=True) + "\n",
            PERMISSION_JSON: json.dumps(permission_payload, indent=2, sort_keys=True) + "\n",
            COMMAND_DOC: "\n".join(command_lines) + "\n",
            PERMISSION_DOC: "\n".join(permission_lines) + "\n"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in render().items():
        if args.write:
            path.write_text(expected, encoding="utf-8", newline="\n")
        elif not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        print("ERROR: stale M12 inventories: " + ", ".join(stale), file=sys.stderr)
        return 1
    print(f"M12 inventories PASS: {len(inventory())} actions and GUI pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
