#!/usr/bin/env python3
"""Generate deterministic through-M13 command and permission inventories."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import m12_inventories

ROOT = Path(__file__).resolve().parents[2]
COMMAND_JSON = ROOT / "build/m13-command-inventory.json"
PERMISSION_JSON = ROOT / "build/m13-permission-inventory.json"
COMMAND_DOC = ROOT / "docs/COMMANDS.md"
PERMISSION_DOC = ROOT / "docs/PERMISSIONS.md"

ROWS = (
    ("objectives", "view", "objectives.view", False, ("ZBW-PROG-010",)),
    ("quests", "active", "quests.view", False, ("ZBW-PROG-009",)),
    ("quests", "completed", "quests.view", False, ("ZBW-PROG-009",)),
    ("achievements", "view", "achievements.view", False, ("ZBW-PROG-012",)),
    ("challenges", "view", "challenges.view", False, ("ZBW-PROG-013",)),
    ("battlepass", "view", "battlepass.view", False, ("ZBW-PROG-013",)),
    ("battlepass", "tiers", "battlepass.view", False, ("ZBW-PROG-013",)),
    ("rewards", "claim", "rewards.claim", True, ("ZBW-PROG-011",)),
    ("admin progression", "inspect", "objectives.manage", False, ("ZBW-PROG-010",)),
    ("admin quest", "assign", "quests.manage", True, ("ZBW-PROG-009",)),
    ("admin quest", "remove", "quests.manage", True, ("ZBW-PROG-009",)),
    ("admin achievement", "grant", "achievements.manage", True, ("ZBW-PROG-012",)),
    ("admin achievement", "inspect", "achievements.manage", False, ("ZBW-PROG-012",)),
    ("admin challenge", "modify", "challenges.manage", True, ("ZBW-PROG-013",)),
    ("admin season", "inspect", "battlepass.manage", False, ("ZBW-PROG-013",)),
    ("admin season", "manage", "battlepass.manage", True, ("ZBW-PROG-013",)),
    ("admin progression", "audit", "progression.audit", False,
     ("ZBW-PROG-009", "ZBW-PROG-010", "ZBW-PROG-012", "ZBW-PROG-013")),
)


def inventory() -> list[dict[str, object]]:
    rows = list(m12_inventories.inventory())
    for family, operation, permission, destructive, requirements in ROWS:
        slug = family.replace(" ", "-")
        rows.append({"action_id": f"m13/{slug}/{operation}",
                     "command": f"/zbw {family} {operation}",
                     "gui_page": f"zartra:m13/{slug}/{operation}",
                     "permission": f"zartrabedwars.{permission}",
                     "destructive": destructive,
                     "requirement_ids": list(requirements)})
    if len(rows) != 174 or len({row["action_id"] for row in rows}) != 174:
        raise ValueError("through-M13 inventory must contain 174 unique actions")
    return rows


def render() -> dict[Path, str]:
    rows = inventory()
    permissions = sorted({str(row["permission"]) for row in rows})
    commands = {"schema_version": 1, "milestone": "M13", "baseline": 157,
                "additive": 17, "count": 174, "commands": rows}
    permission_payload = {"schema_version": 1, "milestone": "M13", "baseline": 157,
                          "additive_nodes": 12, "count": len(permissions),
                          "authorization_source": "M03 AuthorizationService",
                          "permissions": permissions}
    command_lines = ["# Command inventory", "",
                     "Generated by `tools/validation/m13_inventories.py`; manual edits are rejected.",
                     "All 174 action paths dispatch through M09 and central M03 authorization.", "",
                     "| Command | Action | GUI parity page | Permission | Confirmation |",
                     "|---|---|---|---|---|"]
    for row in rows:
        confirmation = "required" if row["destructive"] else "not required"
        command_lines.append(f"| `{row['command']}` | `{row['action_id']}` | "
                             f"`{row['gui_page']}` | `{row['permission']}` | {confirmation} |")
    permission_lines = ["# Permission inventory", "",
                        "Generated by `tools/validation/m13_inventories.py`; manual edits are rejected.",
                        "All nodes are deny-by-default and revalidated at execution time by M03 authorization.", "",
                        "| Permission | Surface | Enforcement |", "|---|---|---|"]
    permission_lines.extend(f"| `{permission}` | command and GUI | execution-time M03 authorization |"
                            for permission in permissions)
    return {COMMAND_JSON: json.dumps(commands, indent=2, sort_keys=True) + "\n",
            PERMISSION_JSON: json.dumps(permission_payload, indent=2, sort_keys=True) + "\n",
            COMMAND_DOC: "\n".join(command_lines) + "\n",
            PERMISSION_DOC: "\n".join(permission_lines) + "\n"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in render().items():
        if args.write:
            path.write_text(expected, encoding="utf-8", newline="\n")
        elif not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        print("ERROR: stale M13 inventories: " + ", ".join(stale))
        return 1
    print("M13 inventories verified: 174 actions, 12 additive permission nodes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
