#!/usr/bin/env python3
"""Generate deterministic through-M14 command and permission inventories."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import m13_inventories

ROOT = Path(__file__).resolve().parents[2]
COMMAND_JSON = ROOT / "build/m14-command-inventory.json"
PERMISSION_JSON = ROOT / "build/m14-permission-inventory.json"
COMMAND_DOC = ROOT / "docs/COMMANDS.md"
PERMISSION_DOC = ROOT / "docs/PERMISSIONS.md"

ROWS = (
    ("cosmetics", "view", "cosmetics.view", False, ("ZBW-PROG-006", "ZBW-PROG-007", "ZBW-PROG-008")),
    ("cosmetics", "categories", "cosmetics.view", False, ("ZBW-PROG-006", "ZBW-PROG-007", "ZBW-PROG-008")),
    ("cosmetics", "rarities", "cosmetics.view", False, ("ZBW-PROG-006", "ZBW-PROG-007", "ZBW-PROG-008")),
    ("cosmetics", "equip", "cosmetics.view", True, ("ZBW-PROG-006", "ZBW-PROG-007", "ZBW-PROG-008")),
    ("profile", "view", "profile", False, ("ZBW-PROG-014",)),
    ("profile", "settings", "profile", True, ("ZBW-PROG-014",)),
    ("profile", "privacy", "profile", True, ("ZBW-PROG-014",)),
    ("campaigns", "active", "campaigns", False, ("ZBW-PROG-014",)),
    ("admin cosmetics", "inspect", "cosmetics.manage", False, ("ZBW-PROG-006", "ZBW-PROG-007")),
    ("admin cosmetics", "grant", "cosmetics.manage", True, ("ZBW-PROG-006", "ZBW-PROG-007")),
    ("admin cosmetics", "manage", "cosmetics.manage", True, ("ZBW-PROG-006", "ZBW-PROG-007")),
    ("admin campaigns", "manage", "campaigns.manage", True, ("ZBW-PROG-014",)),
    ("admin profile", "inspect", "profiles.manage", False, ("ZBW-PROG-014",)),
    ("admin profile", "audit", "profiles.manage", False, ("ZBW-PROG-014",)),
)


def inventory() -> list[dict[str, object]]:
    rows = list(m13_inventories.inventory())
    for family, operation, permission, destructive, requirements in ROWS:
        slug = family.replace(" ", "-")
        rows.append({
            "action_id": f"m14/{slug}/{operation}",
            "command": f"/zbw {family} {operation}",
            "gui_page": f"zartra:m14/{slug}/{operation}",
            "permission": f"zartrabedwars.{permission}",
            "destructive": destructive,
            "requirement_ids": list(requirements),
        })
    if len(rows) != 188 or len({row["action_id"] for row in rows}) != 188:
        raise ValueError("through-M14 inventory must contain 188 unique actions")
    return rows


def render() -> dict[Path, str]:
    rows = inventory()
    permissions = sorted({str(row["permission"]) for row in rows})
    command_lines = ["# Command inventory", "",
                     "Generated by `tools/validation/m14_inventories.py`; manual edits are rejected.",
                     "All 188 action paths dispatch through M09 and central M03 authorization.", "",
                     "| Command | Action | GUI parity page | Permission | Confirmation |",
                     "|---|---|---|---|---|"]
    for row in rows:
        confirmation = "required" if row["destructive"] else "not required"
        command_lines.append(f"| `{row['command']}` | `{row['action_id']}` | "
                             f"`{row['gui_page']}` | `{row['permission']}` | {confirmation} |")
    permission_lines = ["# Permission inventory", "",
                        "Generated by `tools/validation/m14_inventories.py`; manual edits are rejected.",
                        "All nodes are deny-by-default and revalidated at execution time by M03 authorization.", "",
                        "| Permission | Surface | Enforcement |", "|---|---|---|"]
    permission_lines.extend(f"| `{permission}` | command and GUI | execution-time M03 authorization |"
                            for permission in permissions)
    return {
        COMMAND_JSON: json.dumps({"schema_version": 1, "milestone": "M14", "baseline": 174,
                                 "additive": 14, "count": 188, "commands": rows}, indent=2, sort_keys=True) + "\n",
        PERMISSION_JSON: json.dumps({"schema_version": 1, "milestone": "M14", "baseline": 174,
                                    "additive_nodes": 6, "count": len(permissions),
                                    "authorization_source": "M03 AuthorizationService",
                                    "permissions": permissions},
                                   indent=2, sort_keys=True) + "\n",
        COMMAND_DOC: "\n".join(command_lines) + "\n",
        PERMISSION_DOC: "\n".join(permission_lines) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, expected in render().items():
        if args.write:
            path.write_text(expected, encoding="utf-8", newline="\n")
        elif not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        print("ERROR: stale M14 inventories: " + ", ".join(stale))
        return 1
    print("M14 inventories verified: 188 actions, 6 additive permission nodes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
